# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ce9c9dbbaebd2c48a05c644b7ba3690080ab911092e8e406b598e6893e4062d183f3d0653fc64ab3e1ceed5fb36308a7a3165284df2513c1471922badb14249

test:
  secret_key_base: 9e1138ee762d8c7558c7e1f3fe09cbb19c5517bfd316ec83b2cb09239036c662f9dabac92af1d1ce414b9047acdc5a46ec9293a2c11695c22894538f12f163a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
