# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 734b06fa398b7bb8fbeb19eabd07b062a9a4e50f0902215d7848f3ecdd8e6eb9e0e75886a2280dd27aeeb6609c533297bfb1efd4d7fa3fd5ae53521dd177e589

test:
  secret_key_base: 91e3a1e7c644fcd58e9e1931d42a47bade5bb7e59048a21ff2f21c4cdfaf0853e80c004ff2f8ec57305f8236a4701cbf843e91b235e09fa3a60ed731544f76a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
